from models.module.Discriminator import Discriminator
from models.module.Discriminator_Predictor import Discriminator_Predictor
from models.module.Discriminator_Predictor_IMDB import Discriminator_Predictor_IMDB
from models.module.Generator import Generator
from models.module.Generator_sigmoid import Generator_sigmoid
from models.module.Generator_no_inject import Generator_no_inject
from models.module.Generator_no_inject_sigmoid import Generator_no_inject_sigmoid
from models.module.Predictor import Predictor
from models.module.basenet import ResNet18  
from models.module.ColorPredictor import ColorPredictor 